### ISSUE TITLE
"OutputEqual" Assertion Validation Fails for Integer Input

### ISSUE THREAD

**Issue by najose** [schrodinger/infra-tester#4]
The below assertion fails validation because `value` expects a string but when unmarshelling and decoding it's treated as an integer and panics because it was expecting a string. This can worked around by quoting the 10. But it should be possible to consider this field weakly typed somehow so that integers would be converted to strings.

E.g assertion the fails validation:
```yaml
  - type: OutputEqual
    output_name: count
    value: 10                          # value: '10' works
```

See:
- WeakDecode: https://pkg.go.dev/github.com/mitchellh/mapstructure@v1.5.0#WeakDecode
- Example: https://pkg.go.dev/github.com/mitchellh/mapstructure@v1.5.0#example-Decode-WeaklyTypedInput
