### ISSUE TITLE
Provide Optional Field to Give an Assertion a Name

### ISSUE THREAD

**Issue by najose** [schrodinger/infra-tester#6]
It might be helpful to optionally provide a useful custom name for an assertion. For example:
```yaml
- name: MustAddOneResource      # If this field is present the test summary would show this name.
  type: ResourcesAffected
  added: 1
```
