### ISSUE TITLE
Allow "OutputEqual" Assertion to Handle More Complex Data Structure

### ISSUE THREAD

**Issue by najose** [schrodinger/infra-tester#7]
As of now, OutputEqual can only compare string. It would be good to have a mechanism where we can compare maps, lists, strings, integers or combination of any of these. This would make OutputEqual far more useful by helping us avoid write lots of output blocks in the test terraform code for any output that's not a plain string.

So far example, it would be nice to have:
```yaml
- type: OutputEqual
  output_name: an_output
  value:
    a_map: 
      - that has
      - list of values
    a_string_kv: string
    a_int_kv: 10
    ...
```

And infra-tester could convert it to a generic `map[interface{}]interface{}` and then do a deep comparison of each field with that of terraform output (Assuming we can also convert terraform output to `map[interface{}]interface{}`).

This could also possibly fix #4
